In [2]:
import numpy as np

In [5]:
# Memory Management in numpy

In [6]:
x = np.array([1, 2, 3])

In [7]:
x.shape

(3,)

In [8]:
x = np.array([[1, 2], [3, 4]])

In [9]:
x.shape

(2, 2)

In [10]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [11]:
x[0]

array([1, 2])

In [12]:
x[0, 0]

1

In [13]:
x[0][0]

1

In [14]:
x.dtype

dtype('int32')

In [15]:
x.strides # (8, 4) -> means: for relocating between dimensions(rows) you have to jump 8 bytes and for moving forward in columns you have to jump 4 bytes

(8, 4)

In [16]:
y = np.random.rand(2, 3, 4)

In [17]:
y

array([[[0.32786753, 0.58186823, 0.67282297, 0.58967309],
        [0.25079152, 0.40079787, 0.58993408, 0.62120799],
        [0.13958301, 0.81171232, 0.03383139, 0.22564327]],

       [[0.688716  , 0.46247001, 0.91622889, 0.84389652],
        [0.63547055, 0.34713489, 0.35679328, 0.3115104 ],
        [0.47405084, 0.27702918, 0.73916668, 0.06758137]]])

In [18]:
y.strides

(96, 32, 8)

In [19]:
y.shape

(2, 3, 4)

In [20]:
c_array = np.random.rand(2, 3, 4)
fortran_array = np.asfortranarray(c_array)

In [33]:
print(
    c_array.strides
    ,'\n',
    fortran_array.strides
    ,'\n',
    c_array == fortran_array
)
print(c_array)
print(fortran_array)

(96, 32, 8) 
 (8, 16, 48) 
 [[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]
[[[0.67392346 0.27975914 0.08218809 0.42933062]
  [0.79619623 0.51924339 0.91677166 0.08390137]
  [0.27323639 0.77371775 0.81488363 0.72299162]]

 [[0.17320389 0.41963338 0.00171298 0.30057247]
  [0.48236198 0.71276354 0.31749991 0.2768147 ]
  [0.56003043 0.8521723  0.90920139 0.30854972]]]
[[[0.67392346 0.27975914 0.08218809 0.42933062]
  [0.79619623 0.51924339 0.91677166 0.08390137]
  [0.27323639 0.77371775 0.81488363 0.72299162]]

 [[0.17320389 0.41963338 0.00171298 0.30057247]
  [0.48236198 0.71276354 0.31749991 0.2768147 ]
  [0.56003043 0.8521723  0.90920139 0.30854972]]]


In [3]:
x = np.array([
    [1, 2],
    [5, 6]
])

In [31]:
# Row sum
np.sum(x[0, :])

10

In [32]:
# Column sum
np.sum(x[:, 0])

6

In [47]:
# First two rows and all (its) columns
y = x[:2, :] # It's a view (a perspective)
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
# Are these two array sharing the same memory
np.may_share_memory(x, y)

True

In [53]:
y = np.empty((2, 2)) # randomly fill
y[:] = x[:2, :]
np.may_share_memory(x, y)

False

In [58]:
xr = np.arange(10, dtype='int8')

In [59]:
xr.shape

(10,)

In [60]:
xr.shape = (2, 5)

In [61]:
xr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int8)

In [62]:
xr.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]], dtype=int8)

In [63]:
xr == xr

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [64]:
(xr == xr).all()

True

In [72]:
x = np.ones((10000,))
y_temp = np.ones((10000*100,))
y = y_temp[::100]

In [68]:
x.strides

(8,)

In [69]:
y.strides

(800,)

In [70]:
np.may_share_memory(x, y)

False

In [71]:
(x == y).all()

True

In [73]:
np.may_share_memory(y_temp, y)

True

In [74]:
# Shapes and axes

In [77]:
np.array([1, 2, 3], dtype=np.int8)

array([1, 2, 3], dtype=int8)

In [40]:
x = np.random.randint(5, size=(3, 3))

In [36]:
x

array([[9, 9, 4],
       [1, 6, 7],
       [6, 7, 8]])

In [11]:
print(np.random.randint.__doc__[:222])


        randint(low, high=None, size=None, dtype=int)

        Return random integers from `low` (inclusive) to `high` (exclusive).

        Return random integers from the "discrete uniform" distribution of
        the s


In [30]:
x.max()

9

In [31]:
x.min()

1

In [32]:
x.mean()

4.444444444444445

In [33]:
x.max(axis=0) # maxes in 0 dimensions

array([6, 8, 9])

In [34]:
x.min(axis=1)

array([1, 2, 2])

In [70]:
x = np.random.randint(5, size=(2, 3, 4))
x

array([[[4, 4, 0, 2],
        [4, 0, 3, 2],
        [4, 4, 0, 3]],

       [[1, 1, 1, 2],
        [2, 0, 2, 0],
        [2, 4, 2, 4]]])

In [71]:
print(
    x.sum(axis=0), # First dimension
    '\n\n',
    x.sum(axis=1), # Second dimension
    '\n\n',
    x.sum(axis=2), # Third dimension
)

[[5 5 1 4]
 [6 0 5 2]
 [6 8 2 7]] 

 [[12  8  3  7]
 [ 5  5  5  6]] 

 [[10  9 11]
 [ 5  4 12]]


In [68]:
# x.shape = 2, 2, 3 # Inplace
# x.reshape(4, 3, 2) # Inplace or if couldn't makes a copy

In [72]:
x.T # Transpose -> will reverse "strides"

array([[[4, 1],
        [4, 2],
        [4, 2]],

       [[4, 1],
        [0, 0],
        [4, 4]],

       [[0, 1],
        [3, 2],
        [0, 2]],

       [[2, 2],
        [2, 0],
        [3, 4]]])

In [74]:
x = x.T
y = x.T
np.may_share_memory(x, y)

True

In [75]:
x

array([[[4, 1],
        [4, 2],
        [4, 2]],

       [[4, 1],
        [0, 0],
        [4, 4]],

       [[0, 1],
        [3, 2],
        [0, 2]],

       [[2, 2],
        [2, 0],
        [3, 4]]])

In [76]:
x.shape = 2, -1

AttributeError: Incompatible shape for in-place modification. Use `.reshape()` to make a copy with the desired shape.

In [77]:
x.reshape(2, -1) # -1 means find it out by yourself

array([[4, 1, 4, 2, 4, 2, 4, 1, 0, 0, 4, 4],
       [0, 1, 3, 2, 0, 2, 2, 2, 2, 0, 3, 4]])

In [78]:
x.flatten() # make it flat (cpies)

array([4, 1, 4, 2, 4, 2, 4, 1, 0, 0, 4, 4, 0, 1, 3, 2, 0, 2, 2, 2, 2, 0,
       3, 4])

In [79]:
x.ravel() # make it flat (faster than .flatten()) (in place calculates)

array([4, 1, 4, 2, 4, 2, 4, 1, 0, 0, 4, 4, 0, 1, 3, 2, 0, 2, 2, 2, 2, 0,
       3, 4])

In [81]:
np.may_share_memory(x.flatten(), x.ravel())

False

In [84]:
x.flat # is a generator and yields|

In [85]:
# Broadcasting

In [86]:
x = np.array([1, 2, 3])
x * 5

array([ 5, 10, 15])

In [87]:
x ** 2

array([1, 4, 9])

In [88]:
x * x

array([1, 4, 9])

In [89]:
np.full(3, 5) # three 5

array([5, 5, 5])

In [93]:
np.repeat(3, 5) # repeat 3 five times

array([3, 3, 3, 3, 3])

In [ ]:
"""
- Rules for broadcasting
    - equal dimensions
    - one of them is one dimension (not what you think!)
"""

In [103]:
x = np.random.randint(5, size=(3, 3))
x

array([[0, 4, 1],
       [3, 4, 4],
       [4, 1, 1]])

In [104]:
x * np.array([2])

array([[0, 8, 2],
       [6, 8, 8],
       [8, 2, 2]])

In [108]:
x * np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

array([[ 0,  8,  3],
       [ 3,  8, 12],
       [ 4,  2,  3]])

In [109]:
x * np.array([1, 2, 3]) # [1, 2, 3] will multiplied in each row

array([[ 0,  8,  3],
       [ 3,  8, 12],
       [ 4,  2,  3]])

In [ ]:
# Needs the dimension of the array you want to multiply in that array be like from the last dimension of that or plus one level higher, like
"""
2, 3, 4
can multiply with
a 4
or a 3, 4
or a 2, 3, 4
"""

In [111]:
# in brodcastings, matric can stretch

In [113]:
x = np.random.randint(9, size=(1, 9))
y = np.random.randint(9, size=(9, 1))

In [114]:
x

array([[8, 6, 1, 0, 1, 8, 6, 4, 0]])

In [115]:
y

array([[5],
       [5],
       [7],
       [2],
       [2],
       [2],
       [7],
       [2],
       [7]])

In [116]:
x * y

array([[40, 30,  5,  0,  5, 40, 30, 20,  0],
       [40, 30,  5,  0,  5, 40, 30, 20,  0],
       [56, 42,  7,  0,  7, 56, 42, 28,  0],
       [16, 12,  2,  0,  2, 16, 12,  8,  0],
       [16, 12,  2,  0,  2, 16, 12,  8,  0],
       [16, 12,  2,  0,  2, 16, 12,  8,  0],
       [56, 42,  7,  0,  7, 56, 42, 28,  0],
       [16, 12,  2,  0,  2, 16, 12,  8,  0],
       [56, 42,  7,  0,  7, 56, 42, 28,  0]])

In [117]:
x + y

array([[13, 11,  6,  5,  6, 13, 11,  9,  5],
       [13, 11,  6,  5,  6, 13, 11,  9,  5],
       [15, 13,  8,  7,  8, 15, 13, 11,  7],
       [10,  8,  3,  2,  3, 10,  8,  6,  2],
       [10,  8,  3,  2,  3, 10,  8,  6,  2],
       [10,  8,  3,  2,  3, 10,  8,  6,  2],
       [15, 13,  8,  7,  8, 15, 13, 11,  7],
       [10,  8,  3,  2,  3, 10,  8,  6,  2],
       [15, 13,  8,  7,  8, 15, 13, 11,  7]])

In [118]:
# Indexing-Slicing

In [119]:
x = np.random.randint(10, size=(3, 4))
x

array([[2, 4, 2, 3],
       [3, 2, 6, 5],
       [1, 3, 4, 3]])

In [120]:
x[0]

array([2, 4, 2, 3])

In [122]:
x[0][0]

2

In [128]:
x[0, :], (x[0, :] == x[0]).all()

(array([2, 4, 2, 3]), True)

In [124]:
x[:, 0]

array([2, 3, 1])

In [129]:
s = slice(2, 3, 4)
s

slice(2, 3, 4)

In [132]:
x[s]

array([[1, 3, 4, 3]])

In [133]:
x[slice(0, 2), :]

array([[2, 4, 2, 3],
       [3, 2, 6, 5]])

In [135]:
l = [1, 2, 3, 3]
l[:] is l

False

In [136]:
np.may_share_memory(x, x[slice(0, 2), :])

True

In [137]:
x[0] # Indexing

array([2, 4, 2, 3])

In [138]:
x[0:1] # Slicing

array([[2, 4, 2, 3]])

In [141]:
x[0].shape

(4,)

In [142]:
x[0:1].shape

(1, 4)

In [143]:
np.equal(x, x[::])

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [144]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 768F-38E6

 Directory of c:\Users\Amir\Desktop\Pytopia ML 2022\00-Practices

10/06/2023  09:46 PM    <DIR>          .
10/06/2023  09:45 PM    <DIR>          ..
10/08/2023  10:58 PM            34,428 3-numpy.ipynb
               1 File(s)         34,428 bytes
               2 Dir(s)  31,159,345,152 bytes free


In [145]:
x

array([[2, 4, 2, 3],
       [3, 2, 6, 5],
       [1, 3, 4, 3]])

In [146]:
x[0] = 0 # Broadcasting

In [147]:
x

array([[0, 0, 0, 0],
       [3, 2, 6, 5],
       [1, 3, 4, 3]])

In [148]:
x.ndim

2

In [151]:
x = np.random.randint(10, size=(3, 4, 3))
x

array([[[4, 0, 9],
        [2, 9, 5],
        [1, 7, 8],
        [2, 8, 3]],

       [[0, 1, 9],
        [5, 0, 1],
        [4, 7, 7],
        [7, 4, 3]],

       [[2, 4, 5],
        [2, 4, 6],
        [3, 5, 4],
        [1, 2, 6]]])

In [154]:
x[:, :2, :2] # All of it in first dimension, two of the second dimension and two of the third dimension

array([[[4, 0],
        [2, 9]],

       [[0, 1],
        [5, 0]],

       [[2, 4],
        [2, 4]]])

In [163]:
x[..., 0, :] # Ellipsis

array([[4, 0, 9],
       [0, 1, 9],
       [2, 4, 5]])

In [164]:
Ellipsis

Ellipsis

In [165]:
np.newaxis # Adds a new (one) dimension

In [166]:
x

array([[[4, 0, 9],
        [2, 9, 5],
        [1, 7, 8],
        [2, 8, 3]],

       [[0, 1, 9],
        [5, 0, 1],
        [4, 7, 7],
        [7, 4, 3]],

       [[2, 4, 5],
        [2, 4, 6],
        [3, 5, 4],
        [1, 2, 6]]])

In [171]:
x[np.newaxis, np.newaxis, ..., np.newaxis]

array([[[[[[4],
           [0],
           [9]],

          [[2],
           [9],
           [5]],

          [[1],
           [7],
           [8]],

          [[2],
           [8],
           [3]]],


         [[[0],
           [1],
           [9]],

          [[5],
           [0],
           [1]],

          [[4],
           [7],
           [7]],

          [[7],
           [4],
           [3]]],


         [[[2],
           [4],
           [5]],

          [[2],
           [4],
           [6]],

          [[3],
           [5],
           [4]],

          [[1],
           [2],
           [6]]]]]])

In [172]:
np.random.randint(10, size=(3, 3))[:, :, np.newaxis]

array([[[0],
        [5],
        [6]],

       [[7],
        [4],
        [3]],

       [[3],
        [0],
        [5]]])

In [174]:
np.arange(10)[:, np.newaxis] * np.arange(11)[np.newaxis, :]

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90]])

In [176]:
x[0, 0, 0] == x[(0, 0, 0)]

True

In [178]:
s = (0 ,0, 0)
x[s] == x[0, 0, 0]

True

In [179]:
# Advanced indexing

In [180]:
x[[0, 0]]

array([[[4, 0, 9],
        [2, 9, 5],
        [1, 7, 8],
        [2, 8, 3]],

       [[4, 0, 9],
        [2, 9, 5],
        [1, 7, 8],
        [2, 8, 3]]])

In [181]:
# Advanced indexing can be complex and it ALWAYS compies not VIEW

In [182]:
x[0, 0]

array([4, 0, 9])

In [183]:
x[(0, 0)]

array([4, 0, 9])

In [184]:
x

array([[[4, 0, 9],
        [2, 9, 5],
        [1, 7, 8],
        [2, 8, 3]],

       [[0, 1, 9],
        [5, 0, 1],
        [4, 7, 7],
        [7, 4, 3]],

       [[2, 4, 5],
        [2, 4, 6],
        [3, 5, 4],
        [1, 2, 6]]])

In [186]:
x[ [0, 1] ] # First and second elements of first dimension

array([[[4, 0, 9],
        [2, 9, 5],
        [1, 7, 8],
        [2, 8, 3]],

       [[0, 1, 9],
        [5, 0, 1],
        [4, 7, 7],
        [7, 4, 3]]])

In [188]:
x[ [0, 2] ] # First and third elements of ffirst dimension

array([[[4, 0, 9],
        [2, 9, 5],
        [1, 7, 8],
        [2, 8, 3]],

       [[2, 4, 5],
        [2, 4, 6],
        [3, 5, 4],
        [1, 2, 6]]])

In [189]:
x[ np.array([0, 2]) ]

array([[[4, 0, 9],
        [2, 9, 5],
        [1, 7, 8],
        [2, 8, 3]],

       [[2, 4, 5],
        [2, 4, 6],
        [3, 5, 4],
        [1, 2, 6]]])

In [191]:
x[ (0, 1), 2 ] # Also advanced

array([[1, 7, 8],
       [4, 7, 7]])

In [192]:
# Anything but [1, 2, 3] or [(1, 2, 3)] indexing is ADVANCED

In [194]:
x[ (0, 1), ] # First row and second row

array([[[4, 0, 9],
        [2, 9, 5],
        [1, 7, 8],
        [2, 8, 3]],

       [[0, 1, 9],
        [5, 0, 1],
        [4, 7, 7],
        [7, 4, 3]]])

In [195]:
# Mask/Masking

In [197]:
x = np.random.randint(10, size=(3, 3))
x

array([[2, 5, 8],
       [0, 5, 1],
       [5, 4, 9]])

In [200]:
mask = np.array([
    [True, False, False],
    [False, True, False],
    [False, False, True]
])
mask

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [202]:
x[mask] # Show only the True parts and it makes a COPY not VIEW

array([2, 5, 9])

In [203]:
x

array([[2, 5, 8],
       [0, 5, 1],
       [5, 4, 9]])

In [204]:
x[:, [True, False, True]] # Also Masking

array([[2, 8],
       [0, 1],
       [5, 9]])

In [205]:
np.isnan(x)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [206]:
np.isnan(mask)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [208]:
np.isnan(
    np.array([1, 2, 0, np.nan])
)

array([False, False, False,  True])

In [209]:
np.NaN

nan

In [210]:
np.nan

nan

In [211]:
~np.isnan(
    np.array([1, 2, 0, np.nan])
)

array([ True,  True,  True, False])

In [213]:
x > 3 # In which indices are greater than 3

array([[False,  True,  True],
       [False,  True, False],
       [ True,  True,  True]])

In [214]:
x[ x > 3 ]

array([5, 8, 5, 5, 4, 9])

In [215]:
x[ x < 3 ]

array([2, 0, 1])

In [216]:
x[ (x>3) & (x<7) ]

array([5, 5, 5, 4])

In [217]:
x[ np.isnan(x) ]

array([], dtype=int32)

In [218]:
x[ ~np.isnan(x) ]

array([2, 5, 8, 0, 5, 1, 5, 4, 9])

In [225]:
a = np.array([1, 2, 3, np.nan, np.nan, 0])
np.isnan(a).nonzero() # Indexes of those are NaN

(array([3, 4], dtype=int64),)

In [226]:
(~np.isnan(a)).nonzero() # Indexes of those are Not NaN

(array([0, 1, 2, 5], dtype=int64),)

In [227]:
a[ (~np.isnan(a)).nonzero() ]

array([1., 2., 3., 0.])

In [231]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [232]:
~np.arange(10)

array([ -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10])

In [233]:
~~np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [234]:
np.arange(10) == 5

array([False, False, False, False, False,  True, False, False, False,
       False])

In [235]:
np.arange(10)[np.arange(10)==6]

array([6])

In [236]:
# Order and Aggregate

In [249]:
x = np.random.randint(10, size=(2, 3))
x

array([[2, 8, 4],
       [5, 9, 1]])

In [239]:
x.T

array([[3, 1],
       [3, 4],
       [7, 4]])

In [240]:
x.transpose()

array([[3, 1],
       [3, 4],
       [7, 4]])

In [260]:
x

array([[2, 8, 4],
       [5, 9, 1]])

In [247]:
x.sort() # Inplace
x

array([[2, 5, 9],
       [0, 8, 8]])

In [261]:
np.sort(x, axis=0)

array([[2, 8, 1],
       [5, 9, 4]])

In [262]:
# axis = dimension
np.sort(x, axis=1)

array([[2, 4, 8],
       [1, 5, 9]])

In [263]:
a = np.random.randint(10, size=(2, 2))
b = np.random.randint(10, size=(2, 2))

In [266]:
a

array([[5, 5],
       [1, 3]])

In [267]:
b

array([[0, 4],
       [4, 8]])

In [268]:
np.concatenate((a, b))

array([[5, 5],
       [1, 3],
       [0, 4],
       [4, 8]])

In [269]:
np.concatenate((a, b), axis=0)

array([[5, 5],
       [1, 3],
       [0, 4],
       [4, 8]])

In [270]:
np.concatenate((a, b), axis=1)

array([[5, 5, 0, 4],
       [1, 3, 4, 8]])

In [271]:
np.concatenate((a, b, a))

array([[5, 5],
       [1, 3],
       [0, 4],
       [4, 8],
       [5, 5],
       [1, 3]])

In [272]:
# np.sort makes a copy

In [274]:
np.sort(a, axis=0)

array([[1, 3],
       [5, 5]])

In [275]:
np.sort(a, axis=1)

array([[5, 5],
       [1, 3]])

In [276]:
a

array([[5, 5],
       [1, 3]])

In [277]:
b

array([[0, 4],
       [4, 8]])

In [280]:
np.hstack((a, b)) # Horizontally stacked

array([[5, 5, 0, 4],
       [1, 3, 4, 8]])

In [282]:
np.vstack((a, b)) # Vertically stacked

array([[5, 5],
       [1, 3],
       [0, 4],
       [4, 8]])

In [283]:
np.std(a)

1.6583123951777

In [284]:
# More on data types

In [285]:
np.dtype

numpy.dtype

In [286]:
np.dtype('i1')

dtype('int8')

In [292]:
np.dtype('<i4')

dtype('int32')

In [293]:
np.dtype('>i4')

dtype('>i4')

In [295]:
np.dtype('i4').type

numpy.int32

In [296]:
np.dtype('i4').name

'int32'

In [297]:
np.unicode_

numpy.str_

In [298]:
# u3 means 3 unicode characters
# u10 means 10 unicode characters

In [300]:
# Custom data types

stdt = np.dtype([
    ('custom-datatype-name', np.unicode_, 10),
    ('grades-dt', np.float64, (2, 3)),
])

In [338]:
x = np.array([
    ('Sarah', (
        # 2x3
        (3, 4, 5),
        (6, 4, 8),
    )),
    ('Amir', (
        # 2x3
        (33, 44, 25),
        (62, 44, 83),
    )),
], dtype=stdt)

In [308]:
x['custom-datatype-name']

array(['Sarah', 'Amir'], dtype='<U10')

In [309]:
x['grades-dt']

array([[[ 3.,  4.,  5.],
        [ 6.,  4.,  8.]],

       [[33., 44., 25.],
        [62., 44., 83.]]])

In [310]:
x['custom-datatype-name'][0]

'Sarah'

In [311]:
x[0]

('Sarah', [[3., 4., 5.], [6., 4., 8.]])

In [312]:
type(x)

numpy.ndarray

In [313]:
type(x[0])

numpy.void

In [324]:
abc = np.array(['A', 'B', 'C'])

In [325]:
abc

array(['A', 'B', 'C'], dtype='<U1')

In [326]:
abc.itemsize

4

In [328]:
abc[0] = 'erty'
abc

array(['e', 'B', 'C'], dtype='<U1')

In [329]:
import numpy as np

In [330]:
np.empty(
    (2,), dtype=('i1, f4, U10')
)

array([(0, 0., ''), (0, 0., '')],
      dtype=[('f0', 'i1'), ('f1', '<f4'), ('f2', '<U10')])

In [333]:
np.empty(
    (2,3), dtype=('i1, f4, U10, ?') # ? Means boolean
)

array([[(0, 0., '', False), (0, 0., '', False), (0, 0., '', False)],
       [(0, 0., '', False), (0, 0., '', False), (0, 0., '', False)]],
      dtype=[('f0', 'i1'), ('f1', '<f4'), ('f2', '<U10'), ('f3', '?')])

In [334]:
np.empty(
    (2,3), dtype=('i1, f4, U10, ?') # ? Means boolean
)['f0'] # f0 Means field one (columns one)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [336]:
np.empty(
    (2,3), dtype=[ ('id', 'i4'), ('name', 'U10') ] # ? Means boolean
)

array([[(0, ''), (0, ''), (0, '')],
       [(0, ''), (0, ''), (0, '')]],
      dtype=[('id', '<i4'), ('name', '<U10')])

In [337]:
np.empty(
    (2,3), dtype=[ ('id', 'i4'), ('name', 'U10') ] # ? Means boolean
)['name']

array([['', '', ''],
       ['', '', '']], dtype='<U10')

In [345]:
y = np.array([
    ('amir', 12, 2, 30),
    ('amir2', 1, 23, 3),
    ('amir22', -1, 52, 13),
    ('amir44', 41, 2, 3),
], dtype=[ ('name', str, 10), ('age', 'i4'), ('power', 'f2'), ('size', 'i2'), ])
y

array([('amir', 12,  2., 30), ('amir2',  1, 23.,  3),
       ('amir22', -1, 52., 13), ('amir44', 41,  2.,  3)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('power', '<f2'), ('size', '<i2')])

In [347]:
y[ y['power']>=23 ]['name']

array(['amir2', 'amir22'], dtype='<U10')

In [348]:
np.sort(y[ y['power']>=23 ], order='power')['name']

array(['amir2', 'amir22'], dtype='<U10')

In [349]:
np.sort(
    y[ y['power']>=23 ],
    order='power'
)['name']

array(['amir2', 'amir22'], dtype='<U10')

In [351]:
np.datetime64('2015-09-09')

numpy.datetime64('2015-09-09')

In [352]:
np.datetime64('2015-9-9')

ValueError: Error parsing datetime string "2015-9-9" at position 5

In [354]:
np.datetime64('2015-09-09').dtype

dtype('<M8[D]')

In [356]:
np.arange('2010', '2023', dtype='datetime64')

array(['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', '2019', '2020', '2021', '2022'], dtype='datetime64[Y]')

In [359]:
np.arange('2010', '2023', dtype='datetime64[M]') # M means Month

array(['2010-01', '2010-02', '2010-03', '2010-04', '2010-05', '2010-06',
       '2010-07', '2010-08', '2010-09', '2010-10', '2010-11', '2010-12',
       '2011-01', '2011-02', '2011-03', '2011-04', '2011-05', '2011-06',
       '2011-07', '2011-08', '2011-09', '2011-10', '2011-11', '2011-12',
       '2012-01', '2012-02', '2012-03', '2012-04', '2012-05', '2012-06',
       '2012-07', '2012-08', '2012-09', '2012-10', '2012-11', '2012-12',
       '2013-01', '2013-02', '2013-03', '2013-04', '2013-05', '2013-06',
       '2013-07', '2013-08', '2013-09', '2013-10', '2013-11', '2013-12',
       '2014-01', '2014-02', '2014-03', '2014-04', '2014-05', '2014-06',
       '2014-07', '2014-08', '2014-09', '2014-10', '2014-11', '2014-12',
       '2015-01', '2015-02', '2015-03', '2015-04', '2015-05', '2015-06',
       '2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12',
       '2016-01', '2016-02', '2016-03', '2016-04', '2016-05', '2016-06',
       '2016-07', '2016-08', '2016-09', '2016-10', 

In [361]:
np.arange('2010', '2023', dtype='datetime64[M]') - np.arange('2012', '2025', dtype='datetime64[M]') # M means Month

array([-24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
       -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
       -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
       -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
       -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
       -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
       -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
       -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
       -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
       -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
       -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
       -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24, -24],
      dtype='timedelta64[M]')

In [362]:
np.arange('2010', '2023', dtype='datetime64[M]').tolist()

[datetime.date(2010, 1, 1),
 datetime.date(2010, 2, 1),
 datetime.date(2010, 3, 1),
 datetime.date(2010, 4, 1),
 datetime.date(2010, 5, 1),
 datetime.date(2010, 6, 1),
 datetime.date(2010, 7, 1),
 datetime.date(2010, 8, 1),
 datetime.date(2010, 9, 1),
 datetime.date(2010, 10, 1),
 datetime.date(2010, 11, 1),
 datetime.date(2010, 12, 1),
 datetime.date(2011, 1, 1),
 datetime.date(2011, 2, 1),
 datetime.date(2011, 3, 1),
 datetime.date(2011, 4, 1),
 datetime.date(2011, 5, 1),
 datetime.date(2011, 6, 1),
 datetime.date(2011, 7, 1),
 datetime.date(2011, 8, 1),
 datetime.date(2011, 9, 1),
 datetime.date(2011, 10, 1),
 datetime.date(2011, 11, 1),
 datetime.date(2011, 12, 1),
 datetime.date(2012, 1, 1),
 datetime.date(2012, 2, 1),
 datetime.date(2012, 3, 1),
 datetime.date(2012, 4, 1),
 datetime.date(2012, 5, 1),
 datetime.date(2012, 6, 1),
 datetime.date(2012, 7, 1),
 datetime.date(2012, 8, 1),
 datetime.date(2012, 9, 1),
 datetime.date(2012, 10, 1),
 datetime.date(2012, 11, 1),
 datetime.da

In [363]:
np.arange('2010', '2023', dtype='datetime64[M]').tolist()[0]

datetime.date(2010, 1, 1)

In [364]:
type(
    np.arange('2010', '2023', dtype='datetime64[M]').tolist()[0]
)

datetime.date

In [365]:
# Practice session

In [370]:
np.empty((2, 3))

array([[3., 4., 5.],
       [6., 4., 8.]])

In [371]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [372]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [373]:
float('infinity')

inf

In [374]:
np.full((2, 3), 13)

array([[13, 13, 13],
       [13, 13, 13]])

In [378]:
np.array([1, 2, 3]).reshape((3, 1))

array([[1],
       [2],
       [3]])

In [379]:
np.full((3, 3), 5, dtype='i1')

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int8)

In [380]:
np.full((3, 3), 5, dtype=int)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [381]:
np.full((3, 3), 5, dtype=int).dtype

dtype('int32')

In [382]:
np.info(np.int8)

 int8()

Signed integer type, compatible with C ``char``.

:Character code: ``'b'``
:Canonical name: `numpy.byte`
:Alias on this platform (win32 AMD64): `numpy.int8`: 8-bit signed integer (``-128`` to ``127``).


Methods:

  all  --  Scalar method identical to the corresponding array attribute.
  any  --  Scalar method identical to the corresponding array attribute.
  argmax  --  Scalar method identical to the corresponding array attribute.
  argmin  --  Scalar method identical to the corresponding array attribute.
  argsort  --  Scalar method identical to the corresponding array attribute.
  astype  --  Scalar method identical to the corresponding array attribute.
  bit_count  --  int8.bit_count() -> int
  byteswap  --  Scalar method identical to the corresponding array attribute.
  choose  --  Scalar method identical to the corresponding array attribute.
  clip  --  Scalar method identical to the corresponding array attribute.
  compress  --  Scalar method identical to the correspond

In [384]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [385]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [387]:
np.iinfo(np.uint8)

iinfo(min=0, max=255, dtype=uint8)

In [388]:
np.array([-1, 2, -3], dtype=np.uint8)

C:\Users\Amir\AppData\Local\Temp\ipykernel_19356\1977696625.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([-1, 2, -3], dtype=np.uint8)
C:\Users\Amir\AppData\Local\Temp\ipykernel_19356\1977696625.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -3 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([-1, 2, -3], dtype=np.uint8)


array([255,   2, 253], dtype=uint8)

In [391]:
np.arange(0, 1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [393]:
np.arange(-3, 3, dtype=np.float64)

array([-3., -2., -1.,  0.,  1.,  2.])

In [394]:
np.arange(-3, 3, dtype='f4')

array([-3., -2., -1.,  0.,  1.,  2.], dtype=float32)

In [395]:
np.arange(2, 8, 0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. ,
       7.2, 7.4, 7.6, 7.8])

In [396]:
np.linspace(0, 100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [397]:
np.linspace(0, 100, num=2)

array([  0., 100.])

In [398]:
np.linspace(0, 100, num=900)

array([  0.        ,   0.11123471,   0.22246941,   0.33370412,
         0.44493882,   0.55617353,   0.66740823,   0.77864294,
         0.88987764,   1.00111235,   1.11234705,   1.22358176,
         1.33481646,   1.44605117,   1.55728587,   1.66852058,
         1.77975528,   1.89098999,   2.00222469,   2.1134594 ,
         2.2246941 ,   2.33592881,   2.44716352,   2.55839822,
         2.66963293,   2.78086763,   2.89210234,   3.00333704,
         3.11457175,   3.22580645,   3.33704116,   3.44827586,
         3.55951057,   3.67074527,   3.78197998,   3.89321468,
         4.00444939,   4.11568409,   4.2269188 ,   4.3381535 ,
         4.44938821,   4.56062291,   4.67185762,   4.78309232,
         4.89432703,   5.00556174,   5.11679644,   5.22803115,
         5.33926585,   5.45050056,   5.56173526,   5.67296997,
         5.78420467,   5.89543938,   6.00667408,   6.11790879,
         6.22914349,   6.3403782 ,   6.4516129 ,   6.56284761,
         6.67408231,   6.78531702,   6.89655172,   7.00

In [399]:
np.linspace(0, 100, num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [400]:
np.linspace(0, 100, num=7) # Linear space splits into 50 by default parts

array([  0.        ,  16.66666667,  33.33333333,  50.        ,
        66.66666667,  83.33333333, 100.        ])

In [401]:
np.arange(-0.5, 0.2, 0.1)

array([-5.00000000e-01, -4.00000000e-01, -3.00000000e-01, -2.00000000e-01,
       -1.00000000e-01, -1.11022302e-16,  1.00000000e-01])

In [405]:
np.diag((9, 9), 7)

array([[0, 0, 0, 0, 0, 0, 0, 9, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [406]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [408]:
np.eye(9, dtype='i1')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [409]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [410]:
np.diag([1, 1, 1, 1])

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [411]:
# .diag means diagonal (movarab)

In [412]:
np.diag([1, 2, 3], k=0)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [413]:
np.diag([1, 2, 3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [414]:
np.diag([1, 2, 3], k=3)

array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [415]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [416]:
np.eye(3, k=10)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [417]:
np.eye(11, k=1)

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [419]:
np.diag(
    np.arange(5)
)

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [420]:
np.diag(
    np.arange(10)
)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [421]:
np.diag(
    np.arange(50)
)

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       [ 0,  0,  2, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 47,  0,  0],
       [ 0,  0,  0, ...,  0, 48,  0],
       [ 0,  0,  0, ...,  0,  0, 49]])

In [422]:
np.diag(
    np.linspace(1, 121, 6)
)

array([[  1.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  25.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  49.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  73.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  97.,   0.],
       [  0.,   0.,   0.,   0.,   0., 121.]])

In [423]:
np.diag(
    np.linspace(1, 121, 7)
)

array([[  1.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  21.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  41.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  61.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  81.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 101.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0., 121.]])

In [424]:
np.diag(
    np.linspace(1, 121, 5)
)

array([[  1.,   0.,   0.,   0.,   0.],
       [  0.,  31.,   0.,   0.,   0.],
       [  0.,   0.,  61.,   0.,   0.],
       [  0.,   0.,   0.,  91.,   0.],
       [  0.,   0.,   0.,   0., 121.]])

In [425]:
np.diag(
    np.linspace(1, 121, 1)
)

array([[1.]])

In [426]:
np.diag(
    np.linspace(1, 121, 21)
)

array([[  1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   7.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  13.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  19.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  25.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  31.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,  37.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],

In [427]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [429]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [430]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [432]:
z = np.eye(10, k=-2)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [433]:
np.diag(z)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [435]:
np.diag(z, k=-2) # -2 ta az mehvar asli miad paeen va on mehvar ro mide

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [437]:
# baraye tozei ha va tozei haye normal ast
np.random.default_rng

<function numpy.random._generator.default_rng>

In [439]:
rng = np.random.default_rng(10) # 10 is seed
rng

Generator(PCG64) at 0x25ECFD2E420

In [440]:
rng.random((3, 3))

array([[0.95600171, 0.20768181, 0.82844489],
       [0.14928212, 0.51280462, 0.1359196 ],
       [0.68903648, 0.84174772, 0.425509  ]])

In [441]:
rng.random((3, 3))

array([[0.956926  , 0.82533291, 0.33821531],
       [0.57576055, 0.75330186, 0.82710394],
       [0.93343847, 0.14499469, 0.74558021]])

In [443]:
rng.standard_normal(10) # standard normal distrbution function

array([ 0.98371534,  0.63004195, -0.23805881, -1.84493988,  0.16957773,
       -0.17597776,  0.07679986,  1.54230411,  0.18368354,  0.27633381])

In [446]:
rng = np.random.default_rng(4324324) # 4324324 is a random seed
rng.random() # same result every time

0.8732887675273913

In [448]:
rng = np.random.default_rng(4324324) # 4324324 is a random seed
rng.random((3, 3)) # same result every time

array([[0.87328877, 0.29749028, 0.25742013],
       [0.57373864, 0.45186259, 0.29384607],
       [0.01654053, 0.57913417, 0.52848958]])

In [449]:
np.full((3, 4), 'pythontopia')

array([['pythontopia', 'pythontopia', 'pythontopia', 'pythontopia'],
       ['pythontopia', 'pythontopia', 'pythontopia', 'pythontopia'],
       ['pythontopia', 'pythontopia', 'pythontopia', 'pythontopia']],
      dtype='<U11')

In [452]:
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [453]:
np.Inf

inf

In [454]:
np.inf

inf

In [455]:
-np.inf

-inf

In [456]:
np.nan

nan

In [457]:
np.full((3, 3), [-np.inf, np.nan, np.inf])

array([[-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf]])

In [458]:
type(np.array([1, 2, 3]))

numpy.ndarray

In [459]:
type(np.array([1, 2, 3])[0])

numpy.int32

In [1]:
# File I/O

In [3]:
import numpy as np
np.timedelta64 # baraye timedelta va ekhtelafe zamani, timezone na ha!

numpy.timedelta64

In [6]:
np.random.randint(0, 365, 1000)

array([102, 227, 316, 203, 165, 305, 194, 347, 164, 343, 330,  59, 298,
       303,  51,  83, 246, 189,  84, 154, 293, 216, 349, 253, 151, 340,
        51, 198, 296,  27, 330, 225, 286, 254, 152,  92,  66,  74,  68,
       230, 239, 187,  79, 289, 173, 284, 217, 350, 341,  35, 168, 316,
        35,  36, 183, 334, 288, 189, 142, 283, 356, 108, 216, 207,  74,
        68, 318, 170,  33,  16, 145, 109, 174,   6, 236, 189, 330, 226,
        58,  73,  81, 119,  18, 326, 112,  79, 158,  56, 234, 103, 129,
       180, 142, 263, 127, 211,  71, 328, 333,  67, 289, 294,  75, 280,
       243, 286, 363,  24, 178, 139, 160,  21,  85, 363,  41, 246,  42,
        15, 120,  66, 267, 119, 348, 309, 109,  70, 278, 333, 252, 323,
        16,  92, 321, 352,  56, 183, 357,  58, 343, 155,  34,  38,  14,
       200,  69, 102, 271, 294, 168, 169,  89,  72, 341, 279, 151, 101,
       295, 203, 363, 103,  25, 119,   6, 180, 358, 212, 301, 203,  89,
        74,  91,   0, 333,  60, 202,  39, 326, 302, 307, 252,  9

In [9]:
days = np.arange(0, 365) * np.timedelta64(1, 'D')
days

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [15]:
date_ = np.datetime64('2023-01-01') + days

In [11]:
np.recarray

numpy.recarray

In [13]:
id_ = np.arange(1, 366)

In [16]:
value_ = np.random.randint(1, 9119, 365)

In [21]:
structured_array = np.array(
    list(zip(id_, value_, date_)),
    dtype=[
        ('id', 'i4'),
        ('value', 'f4'),
        ('date', 'U20')
    ]
)
structured_array

array([(  1, 6721., '2023-01-01'), (  2, 7290., '2023-01-02'),
       (  3, 5553., '2023-01-03'), (  4, 6987., '2023-01-04'),
       (  5, 2025., '2023-01-05'), (  6, 7893., '2023-01-06'),
       (  7, 1907., '2023-01-07'), (  8,  647., '2023-01-08'),
       (  9,   35., '2023-01-09'), ( 10, 1589., '2023-01-10'),
       ( 11, 3421., '2023-01-11'), ( 12, 6451., '2023-01-12'),
       ( 13, 1440., '2023-01-13'), ( 14,  879., '2023-01-14'),
       ( 15, 3475., '2023-01-15'), ( 16, 3203., '2023-01-16'),
       ( 17, 5864., '2023-01-17'), ( 18, 3115., '2023-01-18'),
       ( 19,  808., '2023-01-19'), ( 20, 2958., '2023-01-20'),
       ( 21, 2422., '2023-01-21'), ( 22, 1813., '2023-01-22'),
       ( 23,  784., '2023-01-23'), ( 24,  401., '2023-01-24'),
       ( 25, 1955., '2023-01-25'), ( 26, 2702., '2023-01-26'),
       ( 27, 1361., '2023-01-27'), ( 28, 8280., '2023-01-28'),
       ( 29, 5444., '2023-01-29'), ( 30,  436., '2023-01-30'),
       ( 31,  467., '2023-01-31'), ( 32, 1911., '2023-0

In [24]:
np.core.records.fromarrays(
    [id_, value_, date_],
    names='id, value, date',
    formats='i4, f4, U20'
)

ValueError: array-shape mismatch in array 1 ("value")

In [28]:
np.savetxt('./records.csv', structured_array, fmt='%i, %04f, %s')

In [4]:
import numpy as np
np.genfromtxt

<function numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)>

In [5]:
np.genfromtxt(
    './records.csv',
    dtype='i4, f4, U20'
)

array([(-1, nan, '2023-01-01'), (-1, nan, '2023-01-02'),
       (-1, nan, '2023-01-03'), (-1, nan, '2023-01-04'),
       (-1, nan, '2023-01-05'), (-1, nan, '2023-01-06'),
       (-1, nan, '2023-01-07'), (-1, nan, '2023-01-08'),
       (-1, nan, '2023-01-09'), (-1, nan, '2023-01-10'),
       (-1, nan, '2023-01-11'), (-1, nan, '2023-01-12'),
       (-1, nan, '2023-01-13'), (-1, nan, '2023-01-14'),
       (-1, nan, '2023-01-15'), (-1, nan, '2023-01-16'),
       (-1, nan, '2023-01-17'), (-1, nan, '2023-01-18'),
       (-1, nan, '2023-01-19'), (-1, nan, '2023-01-20'),
       (-1, nan, '2023-01-21'), (-1, nan, '2023-01-22'),
       (-1, nan, '2023-01-23'), (-1, nan, '2023-01-24'),
       (-1, nan, '2023-01-25'), (-1, nan, '2023-01-26'),
       (-1, nan, '2023-01-27'), (-1, nan, '2023-01-28'),
       (-1, nan, '2023-01-29'), (-1, nan, '2023-01-30'),
       (-1, nan, '2023-01-31'), (-1, nan, '2023-02-01'),
       (-1, nan, '2023-02-02'), (-1, nan, '2023-02-03'),
       (-1, nan, '2023-02-04'),

In [6]:
np.genfromtxt(
    './records.csv',
    dtype='i4, f4, U20',
    delimiter=','
)

array([(  1, 6721., ' 2023-01-01'), (  2, 7290., ' 2023-01-02'),
       (  3, 5553., ' 2023-01-03'), (  4, 6987., ' 2023-01-04'),
       (  5, 2025., ' 2023-01-05'), (  6, 7893., ' 2023-01-06'),
       (  7, 1907., ' 2023-01-07'), (  8,  647., ' 2023-01-08'),
       (  9,   35., ' 2023-01-09'), ( 10, 1589., ' 2023-01-10'),
       ( 11, 3421., ' 2023-01-11'), ( 12, 6451., ' 2023-01-12'),
       ( 13, 1440., ' 2023-01-13'), ( 14,  879., ' 2023-01-14'),
       ( 15, 3475., ' 2023-01-15'), ( 16, 3203., ' 2023-01-16'),
       ( 17, 5864., ' 2023-01-17'), ( 18, 3115., ' 2023-01-18'),
       ( 19,  808., ' 2023-01-19'), ( 20, 2958., ' 2023-01-20'),
       ( 21, 2422., ' 2023-01-21'), ( 22, 1813., ' 2023-01-22'),
       ( 23,  784., ' 2023-01-23'), ( 24,  401., ' 2023-01-24'),
       ( 25, 1955., ' 2023-01-25'), ( 26, 2702., ' 2023-01-26'),
       ( 27, 1361., ' 2023-01-27'), ( 28, 8280., ' 2023-01-28'),
       ( 29, 5444., ' 2023-01-29'), ( 30,  436., ' 2023-01-30'),
       ( 31,  467., ' 202

In [8]:
np.genfromtxt(
    './records.csv',
    dtype='i4, f4, U20',
    delimiter=',',
    skip_header=10
)

array([( 11, 3421., ' 2023-01-11'), ( 12, 6451., ' 2023-01-12'),
       ( 13, 1440., ' 2023-01-13'), ( 14,  879., ' 2023-01-14'),
       ( 15, 3475., ' 2023-01-15'), ( 16, 3203., ' 2023-01-16'),
       ( 17, 5864., ' 2023-01-17'), ( 18, 3115., ' 2023-01-18'),
       ( 19,  808., ' 2023-01-19'), ( 20, 2958., ' 2023-01-20'),
       ( 21, 2422., ' 2023-01-21'), ( 22, 1813., ' 2023-01-22'),
       ( 23,  784., ' 2023-01-23'), ( 24,  401., ' 2023-01-24'),
       ( 25, 1955., ' 2023-01-25'), ( 26, 2702., ' 2023-01-26'),
       ( 27, 1361., ' 2023-01-27'), ( 28, 8280., ' 2023-01-28'),
       ( 29, 5444., ' 2023-01-29'), ( 30,  436., ' 2023-01-30'),
       ( 31,  467., ' 2023-01-31'), ( 32, 1911., ' 2023-02-01'),
       ( 33, 3226., ' 2023-02-02'), ( 34, 4184., ' 2023-02-03'),
       ( 35, 5155., ' 2023-02-04'), ( 36,  602., ' 2023-02-05'),
       ( 37, 8814., ' 2023-02-06'), ( 38,  640., ' 2023-02-07'),
       ( 39, 7994., ' 2023-02-08'), ( 40, 3710., ' 2023-02-09'),
       ( 41, 4340., ' 202

In [10]:
stda = np.genfromtxt(
    './records.csv',
    dtype='i4, f4, U20',
    delimiter=',',
    skip_header=10
)
stda.dtype.names = ('id', 'value', 'date')

In [12]:
stda['id']

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 19

In [13]:
stda['date']

array([' 2023-01-11', ' 2023-01-12', ' 2023-01-13', ' 2023-01-14',
       ' 2023-01-15', ' 2023-01-16', ' 2023-01-17', ' 2023-01-18',
       ' 2023-01-19', ' 2023-01-20', ' 2023-01-21', ' 2023-01-22',
       ' 2023-01-23', ' 2023-01-24', ' 2023-01-25', ' 2023-01-26',
       ' 2023-01-27', ' 2023-01-28', ' 2023-01-29', ' 2023-01-30',
       ' 2023-01-31', ' 2023-02-01', ' 2023-02-02', ' 2023-02-03',
       ' 2023-02-04', ' 2023-02-05', ' 2023-02-06', ' 2023-02-07',
       ' 2023-02-08', ' 2023-02-09', ' 2023-02-10', ' 2023-02-11',
       ' 2023-02-12', ' 2023-02-13', ' 2023-02-14', ' 2023-02-15',
       ' 2023-02-16', ' 2023-02-17', ' 2023-02-18', ' 2023-02-19',
       ' 2023-02-20', ' 2023-02-21', ' 2023-02-22', ' 2023-02-23',
       ' 2023-02-24', ' 2023-02-25', ' 2023-02-26', ' 2023-02-27',
       ' 2023-02-28', ' 2023-03-01', ' 2023-03-02', ' 2023-03-03',
       ' 2023-03-04', ' 2023-03-05', ' 2023-03-06', ' 2023-03-07',
       ' 2023-03-08', ' 2023-03-09', ' 2023-03-10', ' 2023-03-

In [15]:
import pickle
pickle.dump([1,2,3,4,5], open('f.bin', 'wb'))

In [16]:
pickle.dumps([1,2,3,4,5])

b'\x80\x04\x95\x0f\x00\x00\x00\x00\x00\x00\x00]\x94(K\x01K\x02K\x03K\x04K\x05e.'

In [17]:
pickle.load(open('f.bin', 'rb'))

[1, 2, 3, 4, 5]

In [18]:
pickle.loads

<function _pickle.loads(data, /, *, fix_imports=True, encoding='ASCII', errors='strict', buffers=())>

In [19]:
a = np.array([1,2,3,4])
np.save('myfile.npy', a)

In [20]:
np.load('myfile.npy')

array([1, 2, 3, 4])

In [21]:
np.save('myfile.npy', a, allow_pickle=False) # by default is False

In [22]:
np.savez(
    'f.npz',
    np.arange(10),
    np.arange(30, 40),
)

In [24]:
np.load('f.npz')

NpzFile 'f.npz' with keys: arr_0, arr_1

In [25]:
np.load('f.npz')['arr_0']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.savez(
    'f.npz',
    x=np.arange(10),
    y=np.arange(30, 40),
)

In [27]:
np.load('f.npz')['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
f,t = np.load('f.npz').values()
f, t

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]))

In [1]:
# Linear Algebra

In [2]:
import numpy as np

In [3]:
np.matrix # 2 Dimensional ndarray

numpy.matrix

In [4]:
np.matrix( np.arange(9).reshape(3, 3) )

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
np.mat( np.arange(9).reshape(3, 3) )

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [7]:
np.mat('0,1,2; 3,4,5; 6,7,8')

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
m = np.mat('0,1,2; 3,4,5; 6,7,8')
m * m # zarbe matrisi hast va ba zarbe ndarray ha fargh mikone

matrix([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [10]:
# . (dot) zarbe matrisi ast

In [12]:
np.multiply(m, m) # zarbe be sorate narray na matrisi

matrix([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])

In [13]:
# @ ham zarbe matrisi ast

In [14]:
m @ m

matrix([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [15]:
m * m

matrix([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [16]:
np.dot(m,m)

matrix([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [19]:
m

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [20]:
m.I

LinAlgError: Singular matrix

In [23]:
# m.I # agar mesle yek seri bashe va beshe az ro ham hesab karedeshon masalan radife aval ro mishe az roye radife dovom va belaks hesab kard

np.matrix( np.random.random(9).reshape(3,3) )

matrix([[0.70053799, 0.98505773, 0.20190764],
        [0.35621783, 0.57978889, 0.17049653],
        [0.16899429, 0.13878801, 0.3128785 ]])

In [28]:
a = np.random.random(9).reshape(3, 3)
a

array([[4.16441290e-01, 1.45246942e-01, 1.03006216e-02],
       [3.59746128e-01, 7.57595390e-01, 2.92995586e-01],
       [3.72698340e-04, 7.47705163e-01, 1.72306727e-01]])

In [29]:
np.linalg.inv(a)

array([[ 2.05468583,  0.40207403, -0.80652949],
       [ 1.43601985, -1.6651778 ,  2.74567254],
       [-6.23588675,  7.22497729, -6.10918077]])

In [33]:
m.A1 # array shode mide flatten

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
m.A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
np.vdot # vertcal dot

<function vdot at 0x000002883FE11EF0>

In [36]:
np.dot

<function dot at 0x000002883FE11D70>

In [37]:
np.outer # outer product

<function outer at 0x000002884E042630>

In [38]:
np.cross # do bordar -> yek bordar ke amode bar jofteshon

<function cross at 0x000002884E042D30>

In [39]:
np.linalg.det # determinan

<function det at 0x000002884E14AD30>

In [41]:
np.linalg.det(m)

0.0

In [42]:
np.linalg.det(a)

-0.04308957071148012

In [43]:
np.linalg.solve

<function solve at 0x000002884E0411B0>

In [46]:
np.linalg.eig # maghadire vizhe

<function eig at 0x000002884E14A4B0>

In [48]:
np.linalg.svd(m)

SVDResult(U=matrix([[-0.13511895,  0.90281571,  0.40824829],
        [-0.49633514,  0.29493179, -0.81649658],
        [-0.85755134, -0.31295213,  0.40824829]]), S=array([1.42267074e+01, 1.26522599e+00, 5.89938022e-16]), Vh=matrix([[-0.4663281 , -0.57099079, -0.67565348],
        [-0.78477477, -0.08545673,  0.61386131],
        [-0.40824829,  0.81649658, -0.40824829]]))

In [49]:
np.allclose

<function allclose at 0x000002884E043130>

In [50]:
np.linalg.qr

<function qr at 0x000002884E14A170>

In [51]:
np.linalg.inv

<function inv at 0x000002884E149D70>

In [52]:
np.poly # chand jomle ey

<function poly at 0x000002884E1A14F0>

In [54]:
np.roots # rishe haye ye moadeleye chand jomle ey ro mide

<function roots at 0x000002884E1A1670>

In [55]:
np.roots([-50, 24]) # -50x + 24 -> x=24/50=12/25

array([0.48])

In [56]:
np.polyval # mohasebeye x

<function polyval at 0x000002884E1A1BF0>

In [58]:
np.polyval([3, -5], 90) # 3x -5 = 90 -> x=265

265

In [60]:
np.polyint # integral

<function polyint at 0x000002884E1A17F0>

In [61]:
np.polyder # derevitive

<function polyder at 0x000002884E1A1970>

In [63]:
print(np.fft.__doc__) # Fourier Transform


Discrete Fourier Transform (:mod:`numpy.fft`)

.. currentmodule:: numpy.fft

The SciPy module `scipy.fft` is a more comprehensive superset
of ``numpy.fft``, which includes only a basic set of routines.

Standard FFTs
-------------

.. autosummary::
   :toctree: generated/

   fft       Discrete Fourier transform.
   ifft      Inverse discrete Fourier transform.
   fft2      Discrete Fourier transform in two dimensions.
   ifft2     Inverse discrete Fourier transform in two dimensions.
   fftn      Discrete Fourier transform in N-dimensions.
   ifftn     Inverse discrete Fourier transform in N dimensions.

Real FFTs
---------

.. autosummary::
   :toctree: generated/

   rfft      Real discrete Fourier transform.
   irfft     Inverse real discrete Fourier transform.
   rfft2     Real discrete Fourier transform in two dimensions.
   irfft2    Inverse real discrete Fourier transform in two dimensions.
   rfftn     Real discrete Fourier transform in N dimensions.
   irfftn    Inverse real