In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
np.random.rand()

0.5488135039273248

In [5]:
X = np.random.rand(100, 3)
w = np.array([1,2,3])

In [6]:
w

array([1, 2, 3])

In [8]:
w.reshape(-1, 1) # -1 means guess the dimension

array([[1],
       [2],
       [3]])

In [13]:
error = np.random.rand(100, 1)

In [14]:
y = X @ w.reshape(-1, 1) + error
y

array([[1.90650562],
       [1.34970436],
       [1.62420921],
       [1.52443673],
       [2.26981434],
       [4.38197027],
       [1.72829793],
       [1.5105309 ],
       [4.76585575],
       [1.7489459 ],
       [3.5529158 ],
       [3.88523376],
       [2.82388768],
       [2.29789789],
       [2.07466955],
       [3.2980684 ],
       [2.88489523],
       [3.40840892],
       [2.404646  ],
       [3.61790145],
       [4.28954193],
       [4.00070479],
       [5.17288046],
       [4.01796757],
       [2.47609057],
       [4.77992594],
       [4.66544857],
       [5.32496061],
       [3.38267937],
       [2.11496899],
       [3.86490447],
       [3.38228845],
       [1.20596537],
       [3.05465742],
       [4.72850573],
       [2.91292353],
       [1.8750537 ],
       [1.35281909],
       [0.71125561],
       [4.32201981],
       [3.26804791],
       [4.59146213],
       [2.67554854],
       [2.91748407],
       [3.05411272],
       [4.13041147],
       [4.34153889],
       [2.681

In [16]:
X = np.hstack((np.ones((100, 1)), X))

In [27]:
def cost_function(X, y, w):
    y_pred = X @ w
    n, d = X.shape
    cost = np.sum((y - y_pred) ** 2) / (2 * n)
    return cost

def line_search(X, y, w, tolerance=0.001):
    old_cost = cost_function(X, y, w)
    step_size = 0.1
    grad = gradient(X, y, w)
    while cost_function(X, y, w - step_size * grad) > (old_cost + tolerance):
        step_size = step_size * 0.5
    return step_size

def gradient(X, y, w):
    n, d = X.shape
    grad = X.T @ ((X @ w) - y) / n
    return grad

def gradient_descent(X, y, num_iter=100):
    n, d = X.shape
    w = np.zeros((d, 1))
    
    for _ in range(num_iter):
        step_size = line_search(X, y, w)
        w = w - step_size * gradient(X, y, w)
    
    return w

gradient_descent(X, y)

array([[1.28557305],
       [0.95627329],
       [1.41008758],
       [1.93967216]])