In [1]:
import numpy as np

In [2]:
from numpy.linalg import inv

In [3]:
X = np.array([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4],
])

In [4]:
y = np.array([1.2, 2.3, 2.3, 3.3])

In [9]:
# w of maximum likelyhood estimation
# @ is matrix multiplication

In [6]:
X.T

array([[1, 1, 1, 1],
       [1, 2, 3, 4]])

In [7]:
X.T @ X

array([[ 4, 10],
       [10, 30]])

In [8]:
inv(X.T @ X)

array([[ 1.5, -0.5],
       [-0.5,  0.2]])

In [10]:
w_mle = inv(X.T @ X) @ X.T @ y

In [11]:
w_mle

array([0.7 , 0.63])