In [26]:
import numpy as np

In [27]:
X = np.array([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4],
])

y = np.array([1.2, 2.3, 2.3, 3.3])

In [28]:
w_mle = np.linalg.inv(X.T @ X) @ X.T @ y
w_mle

array([0.7 , 0.63])

In [29]:
#

In [30]:
# y = 1 + 1/2 * x
e = [-0.3, 0.3, -0.2, 0.3]

In [31]:
# Polynomial Curve Fitting

In [32]:
w = [1, 0.5]
e = [-0.3, 0.3, -0.2, 0.3]
y = X @ w + e

In [33]:
y

array([1.2, 2.3, 2.3, 3.3])

In [53]:
# Polynomial Curve Fitting

# p=2

PHI2 = np.array([
    [1, 1, 1],
    [1, 2, 4],
    [1, 3, 9],
    [1, 4, 16],
])

In [42]:
w_mle = np.linalg.inv(X.T @ X) @ X.T @ y

In [43]:
w_mle

array([0.7 , 0.63])

In [41]:
# error = Sigma( (prediction - RealDataObserve) ^ 2 )

In [45]:
error = np.sum((y - X @ w_mle) ** 2)
error

0.2229999999999998

In [40]:
w_mle_phi2 = np.linalg.inv(PHI2.T @ PHI2) @ PHI2.T @ y

In [47]:
error_phi2 = np.sum((y - PHI2 @ w_mle_phi2) ** 2)
error_phi2

0.2205000000000002

In [48]:
# p=3

In [54]:
# Polynomial Curve Fitting

# p=3

PHI3 = np.array([
    [1, 1, 1, 1],
    [1, 2, 4, 8],
    [1, 3, 9, 27],
    [1, 4, 16, 64],
])

In [55]:
w_mle_phi3 = np.linalg.inv(PHI3.T @ PHI3) @ PHI3.T @ y
w_mle_phi3

array([-3.1 ,  6.6 , -2.65,  0.35])

In [56]:
error_phi3 = np.sum((y - PHI3 @ w_mle_phi3) ** 2)
error_phi3

1.3286854124644085e-22

In [58]:
np.isclose(error_phi3, 0)

True