In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'a': np.random.rand(3),
    's': 1,
    'b': 'Amir',
    'c': pd.Timestamp('20220104'),
    'd': pd.Series([0.1, 0.3, 0.4]).astype('float32'),
    'e': 'asdasdsdasds',
    'f': False,
    'g': pd.Series([1,1,1], dtype='int8'),
})

df

a  s     b          c    d             e      f  g
0  0.528724  1  Amir 2022-01-04  0.1  asdasdsdasds  False  1
1  0.088231  1  Amir 2022-01-04  0.3  asdasdsdasds  False  1
2  0.301261  1  Amir 2022-01-04  0.4  asdasdsdasds  False  1

In [3]:
df.dtypes

a          float64
s            int64
b           object
c    datetime64[s]
d          float32
e           object
f             bool
g             int8
dtype: object

In [4]:
pd.Series([1,2,3]).dtype 

dtype('int64')

In [5]:
pd.Series([1,2,3,'asds']).dtype 

dtype('O')

In [6]:
df.dtypes.value_counts()

object           2
float64          1
int64            1
datetime64[s]    1
float32          1
bool             1
int8             1
Name: count, dtype: int64

In [8]:
# upcasting

# agar dar amaliati, pandas bekhad yek data type general tari taeen kone be bozorg tare va general tare cast mikone va dar nahaiat be object tabdil mikone age majbor bashe

# df1.reindex_like(df2)

In [9]:
df.to_numpy()

array([[0.5287240977465562, 1, 'Amir', Timestamp('2022-01-04 00:00:00'),
        0.10000000149011612, 'asdasdsdasds', False, 1],
       [0.08823124783146497, 1, 'Amir', Timestamp('2022-01-04 00:00:00'),
        0.30000001192092896, 'asdasdsdasds', False, 1],
       [0.30126129821820224, 1, 'Amir', Timestamp('2022-01-04 00:00:00'),
        0.4000000059604645, 'asdasdsdasds', False, 1]], dtype=object)

In [10]:
df.dtypes

a          float64
s            int64
b           object
c    datetime64[s]
d          float32
e           object
f             bool
g             int8
dtype: object

In [13]:
df.to_numpy().dtype

dtype('O')

In [15]:
# df.to_numpy().dtype == 'object'

In [16]:
df.astype('int8')

TypeError: Converting from datetime64[s] to int8 is not supported. Do obj.astype('int64').astype(dtype) instead

In [17]:
df.astype('int64')

ValueError: invalid literal for int() with base 10: 'Amir'

In [19]:
df.astype('O')

a  s     b                    c    d             e      f  g
0  0.528724  1  Amir  2022-01-04 00:00:00  0.1  asdasdsdasds  False  1
1  0.088231  1  Amir  2022-01-04 00:00:00  0.3  asdasdsdasds  False  1
2  0.301261  1  Amir  2022-01-04 00:00:00  0.4  asdasdsdasds  False  1

In [20]:
df.astype(str)

a  s     b           c    d             e      f  g
0   0.5287240977465562  1  Amir  2022-01-04  0.1  asdasdsdasds  False  1
1  0.08823124783146497  1  Amir  2022-01-04  0.3  asdasdsdasds  False  1
2  0.30126129821820224  1  Amir  2022-01-04  0.4  asdasdsdasds  False  1

In [23]:
df.astype(str).loc[0, 'a']

'0.5287240977465562'

In [26]:
df.astype({
    'a': str,
    's': 'float64',
    'c': 'object',
})

a    s     b                    c    d             e  \
0   0.5287240977465562  1.0  Amir  2022-01-04 00:00:00  0.1  asdasdsdasds   
1  0.08823124783146497  1.0  Amir  2022-01-04 00:00:00  0.3  asdasdsdasds   
2  0.30126129821820224  1.0  Amir  2022-01-04 00:00:00  0.4  asdasdsdasds   

       f  g  
0  False  1  
1  False  1  
2  False  1

In [29]:
df.astype({
    'a': str,
    's': 'float64',
    'c': 'object',
}).dtypes

a     object
s    float64
b     object
c     object
d    float32
e     object
f       bool
g       int8
dtype: object

In [30]:
# pd.read_csv('...', dtype='float64')

In [31]:
df.iloc[:]

a  s     b          c    d             e      f  g
0  0.528724  1  Amir 2022-01-04  0.1  asdasdsdasds  False  1
1  0.088231  1  Amir 2022-01-04  0.3  asdasdsdasds  False  1
2  0.301261  1  Amir 2022-01-04  0.4  asdasdsdasds  False  1

In [35]:
df.loc[[0, 1], ['a', 's']]

a  s
0  0.528724  1
1  0.088231  1

In [36]:
df.loc[0, 1, ['a', 's']]

IndexingError: Too many indexers

In [37]:
df.loc[0, ['a', 's']]

a    0.528724
s           1
Name: 0, dtype: object

In [38]:
df.T

0                    1                    2
a             0.528724             0.088231             0.301261
s                    1                    1                    1
b                 Amir                 Amir                 Amir
c  2022-01-04 00:00:00  2022-01-04 00:00:00  2022-01-04 00:00:00
d                  0.1                  0.3                  0.4
e         asdasdsdasds         asdasdsdasds         asdasdsdasds
f                False                False                False
g                    1                    1                    1

In [39]:
df.T.dtypes

0    object
1    object
2    object
dtype: object

In [42]:
df.T.T.dtypes

a    object
s    object
b    object
c    object
d    object
e    object
f    object
g    object
dtype: object

In [43]:
df.T.T.infer_objects().dtypes

a           float64
s             int64
b            object
c    datetime64[ns]
d           float64
e            object
f              bool
g             int64
dtype: object

In [44]:
pd.to_numeric(['1', 4, 4.4])

array([1. , 4. , 4.4])

In [45]:
pd.to_numeric(pd.Series(['1', 5]))

0    1
1    5
dtype: int64

In [47]:
pd.to_numeric(df['a'])

0    0.528724
1    0.088231
2    0.301261
Name: a, dtype: float64

In [48]:
df.astype('int8', errors='ignore')

a  s     b          c  d             e  f  g
0  0  1  Amir 2022-01-04  0  asdasdsdasds  0  1
1  0  1  Amir 2022-01-04  0  asdasdsdasds  0  1
2  0  1  Amir 2022-01-04  0  asdasdsdasds  0  1

In [49]:
pd.to_numeric(['1', 3, 's'])

ValueError: Unable to parse string "s" at position 2

In [50]:
pd.to_numeric(['1', 3, 's'], errors='ignore')

array(['1', 3, 's'], dtype=object)

In [51]:
pd.to_numeric(['1', 3, 's'], errors='coerce')

array([ 1.,  3., nan])

In [52]:
# coerce = as you can, as many and how you can

In [53]:
pd.to_datetime

<function pandas.core.tools.datetimes.to_datetime(arg: 'DatetimeScalarOrArrayConvertible | DictConvertible', errors: 'DateTimeErrorChoices' = 'raise', dayfirst: 'bool' = False, yearfirst: 'bool' = False, utc: 'bool' = False, format: 'str | None' = None, exact: 'bool | lib.NoDefault' = <no_default>, unit: 'str | None' = None, infer_datetime_format: 'lib.NoDefault | bool' = <no_default>, origin: 'str' = 'unix', cache: 'bool' = True) -> 'DatetimeIndex | Series | DatetimeScalar | NaTType | None'>

In [56]:
df['a'].astype('category')

0    0.528724
1    0.088231
2    0.301261
Name: a, dtype: category
Categories (3, float64): [0.088231, 0.301261, 0.528724]

In [60]:
df

a  s     b          c    d             e      f  g
0  0.528724  1  Amir 2022-01-04  0.1  asdasdsdasds  False  1
1  0.088231  1  Amir 2022-01-04  0.3  asdasdsdasds  False  1
2  0.301261  1  Amir 2022-01-04  0.4  asdasdsdasds  False  1

In [61]:
df['tdelta'] = df.c.diff()
df

a  s     b          c    d             e      f  g tdelta
0  0.528724  1  Amir 2022-01-04  0.1  asdasdsdasds  False  1    NaT
1  0.088231  1  Amir 2022-01-04  0.3  asdasdsdasds  False  1 0 days
2  0.301261  1  Amir 2022-01-04  0.4  asdasdsdasds  False  1 0 days

In [62]:
# get columns by their data-types
df.select_dtypes(['bool'])

f
0  False
1  False
2  False

In [64]:
df.select_dtypes(['datetime'])

c
0 2022-01-04
1 2022-01-04
2 2022-01-04

In [65]:
df.select_dtypes(['int8'])

g
0  1
1  1
2  1

In [66]:
df.select_dtypes(['float64'])

a
0  0.528724
1  0.088231
2  0.301261

In [67]:
df.select_dtypes(['bool', 'bool'])

f
0  False
1  False
2  False

In [68]:
df.select_dtypes(include=['bool'])

f
0  False
1  False
2  False

In [69]:
df.select_dtypes(exclude=['bool'])

a  s     b          c    d             e  g tdelta
0  0.528724  1  Amir 2022-01-04  0.1  asdasdsdasds  1    NaT
1  0.088231  1  Amir 2022-01-04  0.3  asdasdsdasds  1 0 days
2  0.301261  1  Amir 2022-01-04  0.4  asdasdsdasds  1 0 days

In [70]:
df.select_dtypes(include=['number'])

a  s    d  g tdelta
0  0.528724  1  0.1  1    NaT
1  0.088231  1  0.3  1 0 days
2  0.301261  1  0.4  1 0 days

In [71]:
df.select_dtypes(include=['timedelta', 'category'])

tdelta
0    NaT
1 0 days
2 0 days

In [72]:
df.select_dtypes(include=['unsignedinteger'])

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [73]:
df.select_dtypes(include=['str'])

TypeError: string dtypes are not allowed, use 'object' instead

In [74]:
df.select_dtypes(include=['object'])

b             e
0  Amir  asdasdsdasds
1  Amir  asdasdsdasds
2  Amir  asdasdsdasds